### ISSUE TITLE
Nuovi testi normativi

### ISSUE THREAD

**Issue by lordnelson86** [duepuntotre/statutto#1]
Salve a tutti

sono un appassionato di diritto marittimo... che ne dite di aggiungere tutte le norme normalmente contenute nei codici della navigazione? 

Uno su tutti, per esempio il Codice della navigazione ed il Regolamento esecutivo parte marittima, e poi...la legge sulla difesa del mare, le norme sulla sicurezza della navigazione 

Sarebbe bellissimo poter disporre di una app che le contenga

Riporto elenco

-codice navigazione R.D. 327/1942, Aggiornato D.L. 194/2009
-Regolamento per l' esecuzione del codice della navigazione (navigazione marittima) approvato con DPR 15 febbraio 1952 n. 328
-legge sulla sicurezza della navigazione legge n.616 del 62
-legge sulla difesa del mare legge 979 del 1982
-legge 53 del 2011 sulle visite PSC
-d.lvo 196 del 2005, come emendato, sul sistema di rapportazione navale

Riporto anche altre leggi speciali, sempre importanti

Legge 4/2012

Legge 172  del 2003

dlvo 171/2005

Dpr 134 del 2005

Dlvo 182 del 2003

Dm 218 del 2002

Dlvo 28 del 2001

Dpr 135 del 2000

dlvo 45 del 2000

Dlvo 541 del 99

Dlvo 271 del 99

Dlvo 272 del 99

Dlvo 298 del 99

Dm 585 del 95

L 84 del 94

L 220 del 92

dm 8 giugno 89

Dm 27 novembre 86

Dm 4 marzo 83

L1085 del 77

Dpr 816 del 77

L313 del 80

L438 del 82

Dm 31 agosto 68

L 613 del 67

L 690 del 40

Resto a disposizione

Ringrazio

Buonasera,

**Comment by duepuntotre** [comment]
I testi di Statutto possono essere modificati e/o aggiornati, aggiunti e annotati.

E' possibile contribuire attraverso GitHub in maniera del tutto autonoma.

Grazie
